// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwVsejCSvtJ1hXdTPXJQuvRsBembfLBc4',
    appId: '1:1032477261150:web:8e6f276081096a44d7a3cf',
    messagingSenderId: '1032477261150',
    projectId: 'study-planner-260721-1286',
    authDomain: 'study-planner-260721-1286.firebaseapp.com',
    storageBucket: 'study-planner-260721-1286.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1s88dYEFShH3Qhoy9dLXd7uWeicN-2I',
    appId: '1:1032477261150:android:71808cb274b92c46d7a3cf',
    messagingSenderId: '1032477261150',
    projectId: 'study-planner-260721-1286',
    storageBucket: 'study-planner-260721-1286.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUgB09kuSxcMZsofB1fHPFCYwHOUxHVSs',
    appId: '1:1032477261150:ios:f16894940478a8abd7a3cf',
    messagingSenderId: '1032477261150',
    projectId: 'study-planner-260721-1286',
    storageBucket: 'study-planner-260721-1286.firebasestorage.app',
    iosBundleId: 'com.wapertech.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUgB09kuSxcMZsofB1fHPFCYwHOUxHVSs',
    appId: '1:1032477261150:ios:f16894940478a8abd7a3cf',
    messagingSenderId: '1032477261150',
    projectId: 'study-planner-260721-1286',
    storageBucket: 'study-planner-260721-1286.firebasestorage.app',
    iosBundleId: 'com.wapertech.studyPlanner',
  );
}
